
# The ops-only flag is used if the permissions system is set to Basic, and specifies which actions
# should be restricted to ops. If any other permissions system is specified, it is ignored.
# Valid permission systems: Basic, Permissions, GroupManager, WorldEdit, Auto

permissions:
  system: Basic
  ops-only:
   - general.time.set
   - general.teleport
   - general.teleport.other
   - general.teleport.coords
   - general.teleport.other.mass
   - general.summon
   - general.give
   - general.give.infinite
   - general.give.group.notitem
   - general.give.group.bedrock
   - general.give.group.fluid
   - general.spawn.set
   - general.spawn.other
   - general.getpos.other
   - general.clear.other
   - general.take.other
   - general.heal
   - general.mspawn
   - general.admin

# This section lets you restrict certain items to particular groups in the /give command.
# The group '.isop' is understood as meaning the person must be an op to request that item.
# The default configuration shown here restricts items that either are not an item (ie they
# have a different ID for the corresponding inventory item) or are duplicates of another
# item (eg the burning furnace). It also restricts bedrock and fluids.
# 
# Note that this only blocks the user from using the /give command to get these items.
# If they are obtained in any other way, there is nothing to prevent the user from
# placing them. Use WorldGuard for that.

give:
  groups:
    notitem: [26, 55, 59, 62, 63, 64, 68, 71, 74, 75, 83, 90, 93, 94]
    bedrock: [7]
    fluid: [8, 9, 10, 11]

playerlist:
  show-health: false
  show-coords: false
  show-world: false